"""
Sequence Mirror — L → D Transformation
========================================

Converts a natural (L-amino acid) protein sequence into its
mirror-image (D-amino acid) counterpart, and generates D-amino
acid SMILES representations.

Why reverse the sequence?
-------------------------
All modern protein structure predictors (ESMFold, AlphaFold,
RoseTTAFold) were trained exclusively on L-protein structures.
They cannot directly predict D-protein folds.

However, a beautiful symmetry comes to the rescue:

    A D-protein made from sequence ``ABCDE`` folds into the
    **mirror image** of the L-protein made from the **reversed**
    sequence ``EDCBA``.

This is because:

1. D-amino acids have **inverted** backbone φ/ψ torsion angles
   compared to L-amino acids.
2. Reversing the sequence direction swaps N→C and C→N termini,
   which combined with the chirality inversion, produces a
   structure that is the mirror image of the original L-fold.
3. After prediction of the reversed sequence, a coordinate
   reflection (x → −x) yields the D-protein structure.

This "reverse-and-reflect" proxy is an approximation.  It works
well for **globular proteins** with defined folds but is less
reliable for intrinsically disordered regions or proteins whose
folding depends heavily on co-translational effects.

**Reference:** Milton et al. (1992) "Total Chemical Synthesis of
a D-Enzyme: The Enantiomers of HIV-1 Protease Show Demonstration
of Reciprocal Chiral Substrate Specificity."

D-amino acid SMILES
--------------------
Each of the 20 standard amino acids has an L and D form.  They
differ only in the stereochemistry at the α-carbon:

* L-form: ``[C@@H]`` at the α-carbon (S-configuration, except Cys)
* D-form: ``[C@H]`` at the α-carbon (R-configuration, except Cys)

Glycine has no stereocenter (the α-carbon has two hydrogens).
Isoleucine and threonine have an additional stereocenter on the
side chain, which is also inverted in the D-form (full mirror).
"""

from __future__ import annotations

import logging
from typing import Optional

from rdkit import Chem, RDLogger
from rdkit.Chem import rdMolDescriptors

logger = logging.getLogger(__name__)
RDLogger.DisableLog("rdApp.*")

# ── Valid amino acid alphabet ───────────────────────────────────────
STANDARD_AA = set("ACDEFGHIKLMNPQRSTVWY")

# ── L-amino acid SMILES (with correct stereochemistry) ──────────────
# These are the free amino acid forms (not peptide-bonded).
# Stereochemistry at the α-carbon follows IUPAC convention.
L_AMINO_ACID_SMILES: dict[str, str] = {
    "G": "NCC(=O)O",                              # Glycine — achiral
    "A": "N[C@@H](C)C(=O)O",                      # Alanine
    "V": "N[C@@H](C(C)C)C(=O)O",                  # Valine
    "L": "N[C@@H](CC(C)C)C(=O)O",                 # Leucine
    "I": "N[C@@H]([C@@H](C)CC)C(=O)O",            # Isoleucine (2 centres)
    "P": "OC(=O)[C@@H]1CCCN1",                    # Proline
    "F": "N[C@@H](Cc1ccccc1)C(=O)O",              # Phenylalanine
    "W": "N[C@@H](Cc1c[nH]c2ccccc12)C(=O)O",      # Tryptophan
    "M": "N[C@@H](CCSC)C(=O)O",                   # Methionine
    "S": "N[C@@H](CO)C(=O)O",                     # Serine
    "T": "N[C@@H]([C@@H](O)C)C(=O)O",             # Threonine (2 centres)
    "C": "N[C@@H](CS)C(=O)O",                     # Cysteine
    "Y": "N[C@@H](Cc1ccc(O)cc1)C(=O)O",           # Tyrosine
    "N": "N[C@@H](CC(=O)N)C(=O)O",                # Asparagine
    "Q": "N[C@@H](CCC(=O)N)C(=O)O",               # Glutamine
    "D": "N[C@@H](CC(=O)O)C(=O)O",                # Aspartate
    "E": "N[C@@H](CCC(=O)O)C(=O)O",               # Glutamate
    "K": "N[C@@H](CCCCN)C(=O)O",                  # Lysine
    "R": "N[C@@H](CCCNC(=N)N)C(=O)O",             # Arginine
    "H": "N[C@@H](Cc1c[nH]cn1)C(=O)O",            # Histidine
}

# ── D-amino acid SMILES (mirror image = invert ALL stereocentres) ──
# Generated by swapping @@ ↔ @ at every chiral centre.
D_AMINO_ACID_SMILES: dict[str, str] = {
    "G": "NCC(=O)O",                              # Glycine — still achiral
    "A": "N[C@H](C)C(=O)O",
    "V": "N[C@H](C(C)C)C(=O)O",
    "L": "N[C@H](CC(C)C)C(=O)O",
    "I": "N[C@H]([C@H](C)CC)C(=O)O",             # Both centres inverted
    "P": "OC(=O)[C@H]1CCCN1",
    "F": "N[C@H](Cc1ccccc1)C(=O)O",
    "W": "N[C@H](Cc1c[nH]c2ccccc12)C(=O)O",
    "M": "N[C@H](CCSC)C(=O)O",
    "S": "N[C@H](CO)C(=O)O",
    "T": "N[C@H]([C@H](O)C)C(=O)O",              # Both centres inverted
    "C": "N[C@H](CS)C(=O)O",
    "Y": "N[C@H](Cc1ccc(O)cc1)C(=O)O",
    "N": "N[C@H](CC(=O)N)C(=O)O",
    "Q": "N[C@H](CCC(=O)N)C(=O)O",
    "D": "N[C@H](CC(=O)O)C(=O)O",
    "E": "N[C@H](CCC(=O)O)C(=O)O",
    "K": "N[C@H](CCCCN)C(=O)O",
    "R": "N[C@H](CCCNC(=N)N)C(=O)O",
    "H": "N[C@H](Cc1c[nH]cn1)C(=O)O",
}

# Three-letter ↔ one-letter mapping
AA_3TO1: dict[str, str] = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V",
}
AA_1TO3: dict[str, str] = {v: k for k, v in AA_3TO1.items()}


# ── Public API ──────────────────────────────────────────────────────

def is_valid_sequence(sequence: str) -> bool:
    """Check whether a string is a valid protein sequence.

    Parameters
    ----------
    sequence : str
        Amino acid sequence in one-letter codes.

    Returns
    -------
    bool
        ``True`` if every character is a standard amino acid.
    """
    return bool(sequence) and all(c in STANDARD_AA for c in sequence.upper())


def mirror_sequence(sequence: str) -> str:
    """Generate the D-protein proxy sequence by reversing.

    The reversed sequence, when folded by an L-protein predictor,
    approximates the mirror-image fold of the D-protein.

    Parameters
    ----------
    sequence : str
        L-protein amino acid sequence (one-letter codes).

    Returns
    -------
    str
        Reversed sequence (proxy for D-protein prediction).

    Raises
    ------
    ValueError
        If the sequence contains non-standard amino acids.

    Examples
    --------
    >>> mirror_sequence("MKFLILF")
    'FLILKFM'
    >>> mirror_sequence("YGGFL")
    'LFGGY'
    """
    seq = sequence.upper().strip()
    if not is_valid_sequence(seq):
        invalid = [c for c in seq if c not in STANDARD_AA]
        raise ValueError(
            f"Non-standard amino acids found: {set(invalid)}. "
            f"Only standard 20 amino acids are supported: {sorted(STANDARD_AA)}"
        )
    return seq[::-1]


def get_l_smiles(residue: str) -> Optional[str]:
    """Get the SMILES string for an L-amino acid.

    Parameters
    ----------
    residue : str
        One-letter amino acid code.

    Returns
    -------
    str or None
        SMILES with correct L-stereochemistry, or ``None`` if
        the residue code is not recognised.
    """
    return L_AMINO_ACID_SMILES.get(residue.upper())


def get_d_smiles(residue: str) -> Optional[str]:
    """Get the SMILES string for a D-amino acid.

    The D-form is the mirror image — all stereocentres are
    inverted compared to the L-form.

    Parameters
    ----------
    residue : str
        One-letter amino acid code.

    Returns
    -------
    str or None
        SMILES with correct D-stereochemistry, or ``None`` if
        the residue code is not recognised.
    """
    return D_AMINO_ACID_SMILES.get(residue.upper())


def sequence_to_smiles(
    sequence: str,
    chirality: str = "L",
) -> list[dict[str, str]]:
    """Convert a protein sequence to per-residue SMILES.

    Generates SMILES for each amino acid in the sequence with
    the specified stereochemistry.  Useful for small peptides;
    for full proteins, use structure prediction instead.

    Parameters
    ----------
    sequence : str
        Amino acid sequence (one-letter codes).
    chirality : str
        ``"L"`` for natural amino acids, ``"D"`` for mirror.

    Returns
    -------
    list[dict]
        List of ``{"residue": "A", "smiles": "N[C@@H](C)C(=O)O",
        "valid": True}`` dicts.

    Examples
    --------
    >>> result = sequence_to_smiles("AG", chirality="D")
    >>> result[0]["smiles"]
    'N[C@H](C)C(=O)O'
    """
    table = L_AMINO_ACID_SMILES if chirality.upper() == "L" else D_AMINO_ACID_SMILES
    results: list[dict[str, str]] = []

    chir = chirality.upper()
    for aa in sequence.upper():
        smi = table.get(aa)
        mol = Chem.MolFromSmiles(smi) if smi else None
        results.append({
            "residue": aa,
            "chirality": chir,
            "smiles": smi or "",
            "valid": mol is not None,
        })

    return results


def verify_mirror_smiles(residue: str) -> dict[str, str | bool]:
    """Verify that L and D SMILES for a residue are valid mirror images.

    Uses RDKit to confirm both SMILES parse correctly and that
    their InChI representations differ only in stereochemistry.

    Parameters
    ----------
    residue : str
        One-letter amino acid code.

    Returns
    -------
    dict
        Verification result with ``l_smiles``, ``d_smiles``,
        ``l_valid``, ``d_valid``, ``is_mirror_pair``.
    """
    l_smi = get_l_smiles(residue)
    d_smi = get_d_smiles(residue)

    l_mol = Chem.MolFromSmiles(l_smi) if l_smi else None
    d_mol = Chem.MolFromSmiles(d_smi) if d_smi else None

    # Glycine has no stereocenter — L and D are identical
    if residue.upper() == "G":
        return {
            "residue": residue.upper(),
            "l_smiles": l_smi or "",
            "d_smiles": d_smi or "",
            "l_valid": l_mol is not None,
            "d_valid": d_mol is not None,
            "valid": l_mol is not None and d_mol is not None,
            "same_formula": True,
            "is_mirror_pair": True,
            "note": "Glycine is achiral — L and D forms are identical.",
        }

    # Check that they have the same molecular formula
    same_formula = False
    if l_mol and d_mol:
        l_formula = rdMolDescriptors.CalcMolFormula(l_mol)
        d_formula = rdMolDescriptors.CalcMolFormula(d_mol)
        same_formula = (l_formula == d_formula)

    return {
        "residue": residue.upper(),
        "l_smiles": l_smi or "",
        "d_smiles": d_smi or "",
        "l_valid": l_mol is not None,
        "d_valid": d_mol is not None,
        "valid": l_mol is not None and d_mol is not None and same_formula,
        "same_formula": same_formula,
        "is_mirror_pair": same_formula,
    }


def reflect_coordinates(
    pdb_string: str,
    axis: str = "x",
) -> str:
    """Reflect PDB coordinates across a plane to get the mirror image.

    After predicting a structure from the reversed sequence using
    an L-protein predictor, the resulting coordinates represent an
    L-protein fold.  To obtain the actual D-protein coordinates,
    we reflect across one axis (e.g., x → −x).

    This is mathematically equivalent to multiplying the coordinate
    matrix by a reflection matrix with determinant −1.

    Parameters
    ----------
    pdb_string : str
        PDB-format string.
    axis : str
        Which axis to negate: ``"x"``, ``"y"``, or ``"z"``.

    Returns
    -------
    str
        PDB string with reflected coordinates.
    """
    axis_idx = {"x": 0, "y": 1, "z": 2}[axis.lower()]
    lines: list[str] = []

    for line in pdb_string.splitlines():
        if line.startswith(("ATOM", "HETATM")) and len(line) >= 54:
            # PDB format: x=30-38, y=38-46, z=46-54
            coords = [
                float(line[30:38]),
                float(line[38:46]),
                float(line[46:54]),
            ]
            coords[axis_idx] = -coords[axis_idx]
            new_line = (
                line[:30]
                + f"{coords[0]:8.3f}{coords[1]:8.3f}{coords[2]:8.3f}"
                + line[54:]
            )
            lines.append(new_line)
        else:
            lines.append(line)

    return "\n".join(lines)
